services:
  accounts:
    image: "saichandkyama/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - saichandkyama
  loans:
    image: "saichandkyama/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - saichandkyama
  cards:
    image: "saichandkyama/cards:v2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - saichandkyama
networks:
  saichandkyama:
    driver: "bridge"
