build:
  version: "3.0"

accounts:
  message: "Welcome to SSP Bank accounts related local APIs "
  contactDetails:
    name: "Saichand Kyama - Developer"
    email: "saichandkyama@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
